# To get this go to your site it Figroll, look at the URL - you'll see the ID
SiteId = "b748c10e-d238-422a-bebf-ee3f0e6e9591"

# Bit more faff to get this - check a GET request made in the Inspector and
# copy the token
UploadKey = "13146ad8-319e-4191-921b-1810cc77cca0:rkmzinLulRIBITEHjP80tcgEm5HhsWut4n10S5puqXVMkqIh"

# Your public folder
PublicFolder = "."
